/*
 * generated by Xtext
 */
package org.nanosite.conceptgraph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CgUiModule extends org.nanosite.conceptgraph.ui.AbstractCgUiModule {
	public CgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
