/*
* generated by Xtext
*/
package org.nanosite.conceptgraph.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CgTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
