/*
* generated by Xtext
*/
package org.nanosite.conceptgraph.ui.contentassist;

import org.nanosite.conceptgraph.ui.contentassist.AbstractCgProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CgProposalProvider extends AbstractCgProposalProvider {

}
