/*
 * generated by Xtext
 */
package org.nanosite.conceptgraph.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.nanosite.conceptgraph.cg.ConceptDef;

/**
 * This class contains custom scoping description.
 *
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 *
 */
public class CgScopeProvider extends AbstractDeclarativeScopeProvider {

//	public IScope scope_FormalParam_name (ConceptDef ctx, EReference ref)
//	{
//		return Scopes.scopeFor(ctx.getParam());
//	}
}
