/*
 * generated by Xtext
 */
package org.nanosite.conceptgraph;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CgRuntimeModule extends org.nanosite.conceptgraph.AbstractCgRuntimeModule {

}
